language: android
jdk:
  - oraclejdk8
  #- openjdk7
android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.2 # 23.0.2 was not available on build
    - build-tools-23.0.1
    - build-tools-23.0.3
    - build-tools-25.0.0
    # The SDK version used to compile your project
    - android-25
    - android-23
    - android-19

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - addon-google_apis-google-23
env:
  - GRADLE_VERSION='3.2.1' GRADLE_PLUGIN_VERSION='2.3.0-alpha2' ANDROID_GRADLE='25.0.0' COMPILE_SDK='25'
  - GRADLE_VERSION='3.1' GRADLE_PLUGIN_VERSION='2.2.2' ANDROID_GRADLE='25.0.0' COMPILE_SDK='25'
  - GRADLE_VERSION='3.1' GRADLE_PLUGIN_VERSION='2.2.1' ANDROID_GRADLE='25.0.0' COMPILE_SDK='25'
  - GRADLE_VERSION='3.0' GRADLE_PLUGIN_VERSION='2.2.1'  ANDROID_GRADLE='23.0.3' COMPILE_SDK='23'
  - GRADLE_VERSION='2.14.1' GRADLE_PLUGIN_VERSION='2.1.3'  ANDROID_GRADLE='23.0.3' COMPILE_SDK='23'
  - GRADLE_VERSION='2.10' GRADLE_PLUGIN_VERSION='2.1.2' ANDROID_GRADLE='23.0.3' COMPILE_SDK='23'
  - GRADLE_VERSION='2.14' GRADLE_PLUGIN_VERSION='2.1.0'  ANDROID_GRADLE='23.0.3' COMPILE_SDK='23'
  #BROKEN - GRADLE_VERSION='2.14' GRADLE_PLUGIN_VERSION='2.0.0'
  #BROKEN - GRADLE_VERSION='2.2.1' GRADLE_PLUGIN_VERSION='1.5.0'
  - GRADLE_VERSION='2.2.1' GRADLE_PLUGIN_VERSION='1.3.1'  ANDROID_GRADLE='23.0.3' COMPILE_SDK='23'
  #BROKEN - GRADLE_VERSION='2.2.1' GRADLE_PLUGIN_VERSION='1.3.0'
#matrix:
#  # default out of the box set
#  exclude:
#    # exclude jdk7 with the 3.0 build because it requires jdk8
#    - jdk: openjdk7
#      env: GRADLE_VERSION=3.0
#      env: GRADLE_PLUGIN_VERSION=2.2.0
#    - jdk: openjdk7
#      env: GRADLE_VERSION=3.1
#      env: GRADLE_PLUGIN_VERSION=2.2.0



  #- GRADLE_VERSION='2.9' GRADLE_PLUGIN_VERSION='1.3.1'
  #- GRADLE_VERSION='2.4' GRADLE_PLUGIN_VERSION='1.3.1'
  #- GRADLE_VERSION='2.6' GRADLE_PLUGIN_VERSION='1.3.1'
  #- GRADLE_VERSION='2.8' GRADLE_PLUGIN_VERSION='1.3.1'

  #- GRADLE_VERSION='2.14.1' GRADLE_PLUGIN_VERSION='2.1.3'
  #- GRADLE_VERSION='2.10' GRADLE_PLUGIN_VERSION='2.0.0'
  #- GRADLE_VERSION='2.11' GRADLE_PLUGIN_VERSION='2.0.0'
  #- GRADLE_VERSION='2.12' GRADLE_PLUGIN_VERSION='2.0.0'
  #- GRADLE_VERSION='2.13' GRADLE_PLUGIN_VERSION='2.0.0'
  #
  #- GRADLE_VERSION='2.11' GRADLE_PLUGIN_VERSION='2.1.2'
  #- GRADLE_VERSION='2.12' GRADLE_PLUGIN_VERSION='2.1.2'
  #- GRADLE_VERSION='2.13' GRADLE_PLUGIN_VERSION='2.1.2'

sudo: required


before_script:
 - sudo apt-get install gnupg2
 - sudo apt-get install rng-tools gnupg-agent pinentry-curses
 #- sudo echo EXTRAOPTIONS=\"-r /dev/random\" >> /etc/conf.d/rngd
 - export RNGD_OPTS="-o /dev/random -r /dev/urandom"
 #- sudo mknod /dev/hwrng c 10 183
 #- ls /dev | grep hwrng
 #- sudo rngd -f
 #- sudo service rngd start
 #setup gpg first
 - which gpg
 - gpg --version
 - gpg --help
 #generate a bonus gpg key for signing
 - gpg --verbose --batch --gen-key ci/gpginput.txt &
 - gpg --list-keys

 - chmod 755 ci/*.sh
 - ci/matrix_switcher.sh

 #setup the maven android sdk stuff
 #- mkdir temp
 #- cd temp
 #- git clone https://github.com/simpligility/maven-android-sdk-deployer
 #- cd maven-android-sdk-deployer
 # -q quite, log level to warn
 # -B batch mode
 # -fn fail never
 # -U force repo updates
 #- mvn clean install -fn -B -U
 #- cd ..
 #- cd ..

#build
script:

  #setup the username/passwords for nexus defaults
  - ci/configure.sh
  - ./gradlew generateMasterKey
  - ./gradlew encryptPassword -Ppassword=admin123 -PstoreField=NEXUS_PASSWORD
  - ./gradlew encryptPassword -Ppassword=abc -PstoreField=GPG_PASSPHRASE

  #build using gradle
  - ./gradlew -version
  #distZip is only needed on gradle 2.2.1 or older
  - ./gradlew clean distZip install -Pprofile=ci
  #verify publish
  - ci/verify.sh
  #make sure the installed jar is executable
  - ci/runApp.sh


  #setup nexus, should this be moved to before script?
  - wget http://download.sonatype.com/nexus/oss/nexus-2.13.0-01-bundle.zip
  - unzip nexus-2.13.0-01-bundle.zip
  - cd nexus-2.13.0-01/bin
  - pwd
  - chmod 755 nexus
  - ./nexus start &
  - pwd
  - cd ..
  - cd ..
  - pwd
  -

  # wait for nexus
  - ci//waitForNexus.sh

  # build with signatures and publish
  - ./gradlew publishArtifacts -Pprofile=sources,javadoc
  # verify correctness
  - ci/verifySignatures.sh

  #build the site
  - ./gradlew siteWar
  - ci/verifySite.sh

  #stop nexus
  - cd nexus-2.13.0-01/bin
  - ./nexus stop
  - cd ..
  - cd ..


  #- ci/configureIt.sh
  # by this point, we've verified everything gradle related is working
  # now let's build some it projects to confirm stuff is working and dependencies are resolved
  - cd it
  - cd GradleConsumers
  - ./gradlew build
  - cd ..
  - cd MavenConsumers
  - cd ..
  - cd GradleBootstrap
  - ./gradlew bootstrap
  - ./gradlew install -Pprofile=ci
  - ./gradlew site
  #build using maven with integration tests
  #we build 3 times due to issues with the maven-android-plugin. root cause is unknown but seems to be related to how artifacts are resolved for android projects
  #in case you're wondering -fn means fail never, which loosely means, if the build fails, the exit code is always 0, which is basically all CI engines look for.

  #commented out because of maven-android issues on travis, but it does work on my local machine
  #- mvn install -fn -U
  #- mvn install -fn -U
  #- mvn install -U

after_failure:
  # run this on failure
  - cat local.properties
  - cat gradle.properties